version: '2.4'

services:
  app:
    image: nytquestions
    container_name: nytquestions
    restart: always
    build: .
    stdin_open: true
    tty: true
    ports:
      - 9000:9000
    volumes:
      - .:/app
